import { adminSchemaFieldRegistry } from '@/admin/schema/fields/AdminSchemaFieldRegistry';
import type { AdminSchemaFieldDefinition } from '@/admin/schema/fields/schema-field-types';

export const scriptureSchemaFieldDefinitions = [
    {
        schemaFamily: 'scripture',
        entityType: 'book',
        fieldName: 'title',
        columnName: 'title',
        fieldKind: 'title',
        label: 'Book title',
        quickEditable: true,
        structuredEditable: true,
        preferredEditor: 'input',
        preferredPlacement: 'top-right',
    },
    {
        schemaFamily: 'scripture',
        entityType: 'book',
        fieldName: 'description',
        columnName: 'description',
        fieldKind: 'description',
        label: 'Book description',
        quickEditable: true,
        structuredEditable: true,
        preferredEditor: 'textarea',
        preferredPlacement: 'top-right',
    },
    {
        schemaFamily: 'scripture',
        entityType: 'book_section',
        fieldName: 'title',
        columnName: 'title',
        fieldKind: 'title',
        label: 'Book section title',
        quickEditable: true,
        structuredEditable: true,
        preferredEditor: 'input',
        preferredPlacement: 'top-right',
    },
    {
        schemaFamily: 'scripture',
        entityType: 'book_section',
        fieldName: 'slug',
        columnName: 'slug',
        fieldKind: 'slug',
        label: 'Book section slug',
        quickEditable: false,
        structuredEditable: true,
        protected: true,
        preferredEditor: 'structured',
    },
    {
        schemaFamily: 'scripture',
        entityType: 'book_section',
        fieldName: 'number',
        columnName: 'number',
        fieldKind: 'number',
        label: 'Book section number',
        quickEditable: false,
        structuredEditable: true,
        protected: true,
        preferredEditor: 'structured',
    },
    {
        schemaFamily: 'scripture',
        entityType: 'book_section',
        fieldName: 'book_id',
        columnName: 'book_id',
        fieldKind: 'relation',
        label: 'Parent book',
        quickEditable: false,
        structuredEditable: false,
        fullEditOnly: true,
        protected: true,
        preferredEditor: 'full_edit',
    },
    {
        schemaFamily: 'scripture',
        entityType: 'chapter',
        fieldName: 'title',
        columnName: 'title',
        fieldKind: 'title',
        label: 'Chapter title',
        quickEditable: true,
        structuredEditable: true,
        preferredEditor: 'input',
        preferredPlacement: 'top-right',
    },
    {
        schemaFamily: 'scripture',
        entityType: 'chapter_section',
        fieldName: 'title',
        columnName: 'title',
        fieldKind: 'title',
        label: 'Chapter section title',
        quickEditable: true,
        structuredEditable: true,
        preferredEditor: 'input',
        preferredPlacement: 'top-right',
    },
    {
        schemaFamily: 'scripture',
        entityType: 'chapter_section',
        fieldName: 'slug',
        columnName: 'slug',
        fieldKind: 'slug',
        label: 'Chapter section slug',
        quickEditable: false,
        structuredEditable: true,
        protected: true,
        preferredEditor: 'structured',
    },
    {
        schemaFamily: 'scripture',
        entityType: 'chapter_section',
        fieldName: 'number',
        columnName: 'number',
        fieldKind: 'number',
        label: 'Chapter section number',
        quickEditable: false,
        structuredEditable: true,
        protected: true,
        preferredEditor: 'structured',
    },
    {
        schemaFamily: 'scripture',
        entityType: 'chapter_section',
        fieldName: 'chapter_id',
        columnName: 'chapter_id',
        fieldKind: 'relation',
        label: 'Parent chapter',
        quickEditable: false,
        structuredEditable: false,
        fullEditOnly: true,
        protected: true,
        preferredEditor: 'full_edit',
    },
    {
        schemaFamily: 'scripture',
        entityType: 'verse',
        fieldName: 'text',
        columnName: 'text',
        fieldKind: 'long_text',
        label: 'Verse text',
        quickEditable: true,
        structuredEditable: true,
        preferredEditor: 'textarea',
        preferredPlacement: 'top-right',
        constraints: {
            required: true,
            validationHint: 'Verse text is required by the existing identity route.',
        },
    },
    {
        schemaFamily: 'scripture',
        entityType: 'verse',
        fieldName: 'slug',
        columnName: 'slug',
        fieldKind: 'slug',
        label: 'Verse slug',
        quickEditable: false,
        structuredEditable: true,
        protected: true,
        preferredEditor: 'structured',
    },
    {
        schemaFamily: 'scripture',
        entityType: 'verse',
        fieldName: 'number',
        columnName: 'number',
        fieldKind: 'number',
        label: 'Verse number',
        quickEditable: false,
        structuredEditable: true,
        protected: true,
        preferredEditor: 'structured',
    },
    {
        schemaFamily: 'scripture',
        entityType: 'content_block',
        fieldName: 'title',
        columnName: 'title',
        fieldKind: 'title',
        label: 'Block title',
        quickEditable: true,
        structuredEditable: true,
        preferredEditor: 'input',
        preferredPlacement: 'top-right',
    },
    {
        schemaFamily: 'scripture',
        entityType: 'content_block',
        fieldName: 'body',
        columnName: 'body',
        fieldKind: 'long_text',
        label: 'Block body',
        quickEditable: true,
        structuredEditable: true,
        preferredEditor: 'textarea',
        preferredPlacement: 'top-right',
    },
] as const satisfies readonly AdminSchemaFieldDefinition[];

adminSchemaFieldRegistry.registerMany(scriptureSchemaFieldDefinitions);
