<?php

namespace App\Support\Scripture\Admin\Registry\Definitions;

use App\Models\Verse;
use App\Support\Scripture\Admin\Registry\AdminEditMode;
use App\Support\Scripture\Admin\Registry\AdminEditModePolicy;
use App\Support\Scripture\Admin\Registry\AdminEntityDefinition;
use App\Support\Scripture\Admin\Registry\AdminFieldClassification;
use App\Support\Scripture\Admin\Registry\AdminFieldDefinition;
use App\Support\Scripture\Admin\Registry\AdminFieldGroup;
use App\Support\Scripture\Admin\Registry\AdminMethodFamily;
use App\Support\Scripture\Admin\Registry\AdminRegionDefinition;
use App\Support\Scripture\Admin\Registry\AdminRegionMethodDefinition;

class VerseAdminEntityDefinitionProvider extends AdminEntityDefinitionProvider
{
    public function key(): string
    {
        return 'verse';
    }

    public function definition(): AdminEntityDefinition
    {
        return new AdminEntityDefinition(
            key: 'verse',
            label: 'Verse',
            primaryModel: Verse::class,
            primaryTable: 'verses',
            editModePolicy: new AdminEditModePolicy([
                AdminEditMode::CONTEXTUAL => [
                    'label' => 'Contextual Edit',
                    'status' => 'active',
                    'description' => 'Fast editing for verse meta and public note blocks.',
                    'warning' => null,
                ],
                AdminEditMode::FULL => [
                    'label' => 'Full Editorial Edit',
                    'status' => 'active',
                    'description' => 'Protected workspace for verse meta and supporting note blocks.',
                    'warning' => null,
                ],
                AdminEditMode::CANONICAL => [
                    'label' => 'Canonical Protected Edit',
                    'status' => 'active',
                    'description' => 'Protected workflow for core verse text and identity.',
                    'warning' => null,
                ],
            ]),
            fields: [
                'canonical_slug' => $this->canonicalField(
                    key: 'canonical_slug',
                    label: 'Verse slug',
                    source: 'verses.slug',
                ),
                'canonical_number' => $this->canonicalField(
                    key: 'canonical_number',
                    label: 'Verse number',
                    source: 'verses.number',
                ),
                'canonical_text' => $this->canonicalField(
                    key: 'canonical_text',
                    label: 'Verse text',
                    source: 'verses.text',
                    helpText: 'Protected canonical text shown on the public verse surface.',
                ),
                'primary_speaker_character_id' => new AdminFieldDefinition(
                    key: 'primary_speaker_character_id',
                    label: 'Primary speaker',
                    source: 'verse_meta.primary_speaker_character_id',
                    type: 'relation',
                    validationRules: ['nullable', 'integer', 'exists:characters,id'],
                    editModes: [AdminEditMode::CONTEXTUAL, AdminEditMode::FULL],
                    classification: AdminFieldClassification::EDITORIAL,
                    group: AdminFieldGroup::EDITORIAL,
                ),
                'primary_listener_character_id' => new AdminFieldDefinition(
                    key: 'primary_listener_character_id',
                    label: 'Primary listener',
                    source: 'verse_meta.primary_listener_character_id',
                    type: 'relation',
                    validationRules: ['nullable', 'integer', 'exists:characters,id'],
                    editModes: [AdminEditMode::CONTEXTUAL, AdminEditMode::FULL],
                    classification: AdminFieldClassification::EDITORIAL,
                    group: AdminFieldGroup::EDITORIAL,
                ),
                'difficulty_level' => new AdminFieldDefinition(
                    key: 'difficulty_level',
                    label: 'Difficulty level',
                    source: 'verse_meta.difficulty_level',
                    type: 'text',
                    validationRules: ['nullable', 'string', 'max:255'],
                    editModes: [AdminEditMode::CONTEXTUAL, AdminEditMode::FULL],
                    classification: AdminFieldClassification::EDITORIAL,
                    group: AdminFieldGroup::EDITORIAL,
                ),
                'summary_short' => new AdminFieldDefinition(
                    key: 'summary_short',
                    label: 'Summary',
                    source: 'verse_meta.summary_short',
                    type: 'textarea',
                    validationRules: ['nullable', 'string'],
                    editModes: [AdminEditMode::CONTEXTUAL, AdminEditMode::FULL],
                    classification: AdminFieldClassification::EDITORIAL,
                    group: AdminFieldGroup::EDITORIAL,
                ),
                'is_featured' => new AdminFieldDefinition(
                    key: 'is_featured',
                    label: 'Featured verse',
                    source: 'verse_meta.is_featured',
                    type: 'boolean',
                    validationRules: ['required', 'boolean'],
                    editModes: [AdminEditMode::CONTEXTUAL, AdminEditMode::FULL],
                    classification: AdminFieldClassification::EDITORIAL,
                    group: AdminFieldGroup::EDITORIAL,
                ),
                'translation_source_key' => new AdminFieldDefinition(
                    key: 'translation_source_key',
                    label: 'Translation source key',
                    source: 'verse_translations.source_key',
                    type: 'text',
                    validationRules: ['required', 'string', 'max:255'],
                    editModes: [AdminEditMode::FULL],
                    classification: AdminFieldClassification::EDITORIAL,
                    group: AdminFieldGroup::SUPPORTING,
                    helpText: 'Stored source key snapshot for the verse_translations row. This stays on the row even when a linked translation_sources record also exists.',
                ),
                'translation_source_name' => new AdminFieldDefinition(
                    key: 'translation_source_name',
                    label: 'Translation source name',
                    source: 'verse_translations.source_name',
                    type: 'text',
                    validationRules: ['required', 'string', 'max:255'],
                    editModes: [AdminEditMode::FULL],
                    classification: AdminFieldClassification::EDITORIAL,
                    group: AdminFieldGroup::SUPPORTING,
                    helpText: 'Stored display name snapshot for the translation row.',
                ),
                'translation_source_id' => new AdminFieldDefinition(
                    key: 'translation_source_id',
                    label: 'Translation source record',
                    source: 'verse_translations.translation_source_id',
                    type: 'relation',
                    validationRules: ['nullable', 'integer', 'exists:translation_sources,id'],
                    editModes: [AdminEditMode::FULL],
                    classification: AdminFieldClassification::EDITORIAL,
                    group: AdminFieldGroup::SUPPORTING,
                    helpText: 'Optional relation to translation_sources. Selecting a source can prefill source metadata, but the verse row still stores its own source_key, source_name, and language_code snapshot.',
                ),
                'translation_language_code' => new AdminFieldDefinition(
                    key: 'translation_language_code',
                    label: 'Translation language code',
                    source: 'verse_translations.language_code',
                    type: 'text',
                    validationRules: ['required', 'string', 'max:16'],
                    editModes: [AdminEditMode::FULL],
                    classification: AdminFieldClassification::EDITORIAL,
                    group: AdminFieldGroup::SUPPORTING,
                ),
                'translation_text' => new AdminFieldDefinition(
                    key: 'translation_text',
                    label: 'Translation text',
                    source: 'verse_translations.text',
                    type: 'textarea',
                    validationRules: ['required', 'string'],
                    editModes: [AdminEditMode::FULL],
                    classification: AdminFieldClassification::EDITORIAL,
                    group: AdminFieldGroup::SUPPORTING,
                ),
                'translation_sort_order' => new AdminFieldDefinition(
                    key: 'translation_sort_order',
                    label: 'Translation sort order',
                    source: 'verse_translations.sort_order',
                    type: 'integer',
                    validationRules: ['required', 'integer', 'min:0'],
                    editModes: [AdminEditMode::FULL],
                    classification: AdminFieldClassification::EDITORIAL,
                    group: AdminFieldGroup::SUPPORTING,
                ),
                'commentary_source_key' => new AdminFieldDefinition(
                    key: 'commentary_source_key',
                    label: 'Commentary source key',
                    source: 'verse_commentaries.source_key',
                    type: 'text',
                    validationRules: ['required', 'string', 'max:255'],
                    editModes: [AdminEditMode::FULL],
                    classification: AdminFieldClassification::EDITORIAL,
                    group: AdminFieldGroup::SUPPORTING,
                    helpText: 'Stored source key snapshot for the verse_commentaries row.',
                ),
                'commentary_source_name' => new AdminFieldDefinition(
                    key: 'commentary_source_name',
                    label: 'Commentary source name',
                    source: 'verse_commentaries.source_name',
                    type: 'text',
                    validationRules: ['required', 'string', 'max:255'],
                    editModes: [AdminEditMode::FULL],
                    classification: AdminFieldClassification::EDITORIAL,
                    group: AdminFieldGroup::SUPPORTING,
                    helpText: 'Stored display name snapshot for the commentary row.',
                ),
                'commentary_source_id' => new AdminFieldDefinition(
                    key: 'commentary_source_id',
                    label: 'Commentary source record',
                    source: 'verse_commentaries.commentary_source_id',
                    type: 'relation',
                    validationRules: ['nullable', 'integer', 'exists:commentary_sources,id'],
                    editModes: [AdminEditMode::FULL],
                    classification: AdminFieldClassification::EDITORIAL,
                    group: AdminFieldGroup::SUPPORTING,
                    helpText: 'Optional relation to commentary_sources. The verse commentary still stores its own source snapshot fields plus author/title/body content.',
                ),
                'commentary_author_name' => new AdminFieldDefinition(
                    key: 'commentary_author_name',
                    label: 'Commentary author',
                    source: 'verse_commentaries.author_name',
                    type: 'text',
                    validationRules: ['nullable', 'string', 'max:255'],
                    editModes: [AdminEditMode::FULL],
                    classification: AdminFieldClassification::EDITORIAL,
                    group: AdminFieldGroup::SUPPORTING,
                ),
                'commentary_language_code' => new AdminFieldDefinition(
                    key: 'commentary_language_code',
                    label: 'Commentary language code',
                    source: 'verse_commentaries.language_code',
                    type: 'text',
                    validationRules: ['required', 'string', 'max:16'],
                    editModes: [AdminEditMode::FULL],
                    classification: AdminFieldClassification::EDITORIAL,
                    group: AdminFieldGroup::SUPPORTING,
                ),
                'commentary_title' => new AdminFieldDefinition(
                    key: 'commentary_title',
                    label: 'Commentary title',
                    source: 'verse_commentaries.title',
                    type: 'text',
                    validationRules: ['nullable', 'string', 'max:255'],
                    editModes: [AdminEditMode::FULL],
                    classification: AdminFieldClassification::EDITORIAL,
                    group: AdminFieldGroup::SUPPORTING,
                ),
                'commentary_body' => new AdminFieldDefinition(
                    key: 'commentary_body',
                    label: 'Commentary body',
                    source: 'verse_commentaries.body',
                    type: 'textarea',
                    validationRules: ['required', 'string'],
                    editModes: [AdminEditMode::FULL],
                    classification: AdminFieldClassification::EDITORIAL,
                    group: AdminFieldGroup::SUPPORTING,
                ),
                'commentary_sort_order' => new AdminFieldDefinition(
                    key: 'commentary_sort_order',
                    label: 'Commentary sort order',
                    source: 'verse_commentaries.sort_order',
                    type: 'integer',
                    validationRules: ['required', 'integer', 'min:0'],
                    editModes: [AdminEditMode::FULL],
                    classification: AdminFieldClassification::EDITORIAL,
                    group: AdminFieldGroup::SUPPORTING,
                ),
                ...$this->sharedRegisteredNoteBlockFields(),
            ],
            regions: [
                new AdminRegionDefinition(
                    key: 'verse_intro',
                    label: 'Verse intro',
                    surface: 'chapters.verses.show',
                    description: 'Primary published introduction block shown above the canonical verse text.',
                    fieldKeys: array_keys($this->sharedRegisteredNoteBlockFields()),
                    contextualFieldKeys: [
                        'content_block_title',
                        'content_block_body',
                        'content_block_media_url',
                        'content_block_alt_text',
                    ],
                    fullFieldKeys: array_keys($this->sharedRegisteredNoteBlockFields()),
                    canonicalFieldKeys: [],
                    capabilityHint: 'intro',
                    helpText: 'Verse intro is editorial block content. Canonical slug, number, and verse text stay on the separate identity surface.',
                ),
                new AdminRegionDefinition(
                    key: 'verse_notes',
                    label: 'Study notes',
                    surface: 'chapters.verses.show',
                    description: 'Compact editorial metadata attached to the verse.',
                    fieldKeys: [
                        'primary_speaker_character_id',
                        'primary_listener_character_id',
                        'difficulty_level',
                        'summary_short',
                        'is_featured',
                    ],
                    contextualFieldKeys: [
                        'primary_speaker_character_id',
                        'primary_listener_character_id',
                        'difficulty_level',
                        'summary_short',
                        'is_featured',
                    ],
                    fullFieldKeys: [
                        'primary_speaker_character_id',
                        'primary_listener_character_id',
                        'difficulty_level',
                        'summary_short',
                        'is_featured',
                    ],
                    capabilityHint: 'relationships',
                ),
                new AdminRegionDefinition(
                    key: 'translations',
                    label: 'Verse translations',
                    surface: 'chapters.verses.show, chapters.verses.full-edit',
                    description: 'Verse-owned translation rows stored in verse_translations.',
                    fieldKeys: [
                        'translation_source_key',
                        'translation_source_name',
                        'translation_source_id',
                        'translation_language_code',
                        'translation_text',
                        'translation_sort_order',
                    ],
                    contextualFieldKeys: [],
                    fullFieldKeys: [
                        'translation_source_key',
                        'translation_source_name',
                        'translation_source_id',
                        'translation_language_code',
                        'translation_text',
                        'translation_sort_order',
                    ],
                    capabilityHint: 'translation',
                    helpText: 'These rows come directly from verse_translations and can optionally link to translation_sources while still storing verse-local source snapshots.',
                ),
                new AdminRegionDefinition(
                    key: 'commentaries',
                    label: 'Verse commentaries',
                    surface: 'chapters.verses.show, chapters.verses.full-edit',
                    description: 'Verse-owned commentary rows stored in verse_commentaries.',
                    fieldKeys: [
                        'commentary_source_key',
                        'commentary_source_name',
                        'commentary_source_id',
                        'commentary_author_name',
                        'commentary_language_code',
                        'commentary_title',
                        'commentary_body',
                        'commentary_sort_order',
                    ],
                    contextualFieldKeys: [],
                    fullFieldKeys: [
                        'commentary_source_key',
                        'commentary_source_name',
                        'commentary_source_id',
                        'commentary_author_name',
                        'commentary_language_code',
                        'commentary_title',
                        'commentary_body',
                        'commentary_sort_order',
                    ],
                    capabilityHint: 'commentary',
                    helpText: 'These rows come directly from verse_commentaries and can optionally link to commentary_sources while preserving verse-local commentary content.',
                ),
                new AdminRegionDefinition(
                    key: 'content_blocks',
                    label: 'Published notes',
                    surface: 'chapters.verses.show',
                    description: 'Verse-owned editorial note blocks.',
                    fieldKeys: array_keys($this->sharedRegisteredNoteBlockFields()),
                    contextualFieldKeys: ['content_block_title', 'content_block_body'],
                    fullFieldKeys: array_keys($this->sharedRegisteredNoteBlockFields()),
                    capabilityHint: 'content_blocks',
                    helpText: 'Verse uses the shared registered note workflow while keeping ownership scoped to the current verse. Text, quote, and image blocks stay inside this surface; video remains protected.',
                    methods: [
                        new AdminRegionMethodDefinition(
                            family: AdminMethodFamily::CONTENT_BLOCK_CREATE,
                            editModes: [AdminEditMode::CONTEXTUAL, AdminEditMode::FULL],
                            label: 'Verse content-block create',
                        ),
                        new AdminRegionMethodDefinition(
                            family: AdminMethodFamily::CONTENT_BLOCK_EDIT,
                            editModes: [AdminEditMode::CONTEXTUAL, AdminEditMode::FULL],
                            label: 'Verse content-block edit',
                        ),
                        new AdminRegionMethodDefinition(
                            family: AdminMethodFamily::ORDERED_INSERTION,
                            editModes: [AdminEditMode::CONTEXTUAL, AdminEditMode::FULL],
                            label: 'Verse ordered insertion',
                        ),
                        new AdminRegionMethodDefinition(
                            family: AdminMethodFamily::REORDER,
                            editModes: [AdminEditMode::FULL],
                            label: 'Verse content-block reorder',
                            description: 'Uses the shared ordering resolver while Verse stays scoped to registered text, quote, and image note blocks.',
                        ),
                    ],
                ),
            ],
        );
    }
}
