import type { ConsciousAdminActionDefinition } from './conscious-action-types';

const unavailable = (
    reason: string,
): Pick<ConsciousAdminActionDefinition, 'enabled' | 'showInSurfaceMenu' | 'disabledReason'> => ({
    enabled: false,
    showInSurfaceMenu: false,
    disabledReason: reason,
});

const NEEDS_BACKEND = 'Requires a Conscious Admin backend action service.';
const OLD_ENDPOINT_ONLY =
    'Only route-specific legacy service endpoints exist right now.';
const FUTURE = 'Future action; no Conscious Admin backend contract exists yet.';

export const bookSchemaConsciousActions: readonly ConsciousAdminActionDefinition[] =
    [
        {
            key: 'schema_field.edit',
            schemaFamily: 'scripture',
            entityType: 'book',
            family: 'edit',
            label: 'Edit',
            menuGroup: 'content',
            controlLevel: 'field',
            uiMode: 'modal',
            backendStatus: 'available_now',
            risk: 'safe',
            requiredCapability: 'edit',
            backendAction: { type: 'field_route', fieldName: '*' },
            fullEditCategory: 'Basic Content',
            showInSurfaceMenu: true,
            enabled: true,
        },
        {
            key: 'schema_entity.full_edit',
            schemaFamily: 'scripture',
            entityType: 'book',
            family: 'full_edit',
            label: 'Full Edit',
            menuGroup: 'identity',
            controlLevel: 'entity',
            uiMode: 'full_edit',
            backendStatus: 'available_now',
            risk: 'protected',
            requiredCapability: 'full_edit',
            backendAction: { type: 'conscious_full_edit' },
            fullEditCategory: 'All Categories',
            showInSurfaceMenu: true,
            enabled: true,
        },
        ...(['book_section', 'chapter', 'chapter_section', 'verse'] as const)
            .flatMap((entityType) => [
                {
                    key: 'schema_field.edit',
                    schemaFamily: 'scripture',
                    entityType,
                    family: 'edit',
                    label: 'Edit',
                    menuGroup: 'content',
                    controlLevel: 'field',
                    uiMode: 'modal',
                    backendStatus: 'available_now',
                    risk: 'safe',
                    requiredCapability: 'edit',
                    backendAction: { type: 'field_route', fieldName: '*' },
                    fullEditCategory: 'Basic Content',
                    showInSurfaceMenu: true,
                    enabled: true,
                },
                {
                    key: 'schema_entity.full_edit',
                    schemaFamily: 'scripture',
                    entityType,
                    family: 'full_edit',
                    label: 'Full Edit',
                    menuGroup: 'identity',
                    controlLevel: 'entity',
                    uiMode: 'full_edit',
                    backendStatus: 'available_now',
                    risk: 'protected',
                    requiredCapability: 'full_edit',
                    backendAction: { type: 'conscious_full_edit' },
                    fullEditCategory: 'All Categories',
                    showInSurfaceMenu: true,
                    enabled: true,
                },
            ] satisfies ConsciousAdminActionDefinition[]),
        ...(['book', 'book_section', 'chapter', 'chapter_section', 'verse'] as const).map(
            (entityType) =>
                ({
                    key: `${entityType}.identity.edit`,
                    schemaFamily: 'scripture',
                    entityType,
                    family: 'identity',
                    label: 'Edit canonical identity',
                    menuGroup: 'identity',
                    controlLevel: 'entity',
                    uiMode: 'drawer',
                    backendStatus: 'old_endpoint_only',
                    risk: 'protected',
                    requiredCapability: 'manage',
                    backendAction: {
                        type: 'old_endpoint_fallback',
                        routeName: `${entityType}.identity`,
                    },
                    fullEditCategory: 'Canonical Identity',
                    ...unavailable(OLD_ENDPOINT_ONLY),
                }) satisfies ConsciousAdminActionDefinition,
        ),
        ...[
            ['book', 'book_section', 'Add book section'],
            ['book_section', 'chapter', 'Add chapter'],
            ['chapter', 'chapter_section', 'Add chapter section'],
            ['chapter_section', 'verse', 'Add verse'],
        ].map(
            ([entityType, childType, label]) =>
                ({
                    key: `${entityType}.${childType}.create`,
                    schemaFamily: 'scripture',
                    entityType,
                    family: 'create',
                    label,
                    menuGroup: 'structure',
                    controlLevel: 'section',
                    uiMode: 'modal',
                    backendStatus: 'needs_conscious_backend',
                    risk: 'protected',
                    requiredCapability: 'create',
                    backendAction: {
                        type: 'schema_action',
                        actionKey: `${childType}.create`,
                    },
                    fullEditCategory: 'Structure & Parentage',
                    ...unavailable(NEEDS_BACKEND),
                }) satisfies ConsciousAdminActionDefinition,
        ),
        ...[
            ['book', 'Reorder book sections'],
            ['book_section', 'Reorder chapters'],
            ['chapter', 'Reorder chapter sections'],
            ['chapter_section', 'Reorder verses'],
            ['content_block', 'Reorder block'],
            ['media_assignment', 'Reorder media slot'],
            ['verse', 'Reorder support entries'],
        ].map(
            ([entityType, label]) =>
                ({
                    key: `${entityType}.reorder`,
                    schemaFamily: 'scripture',
                    entityType,
                    family: 'reorder',
                    label,
                    menuGroup: 'structure',
                    controlLevel: 'section',
                    uiMode: 'drawer',
                    backendStatus: 'needs_conscious_backend',
                    risk: 'protected',
                    requiredCapability: 'reorder',
                    backendAction: {
                        type: 'schema_action',
                        actionKey: 'reorder',
                    },
                    fullEditCategory: 'Ordering',
                    ...unavailable(NEEDS_BACKEND),
                }) satisfies ConsciousAdminActionDefinition,
        ),
        ...(['book', 'book_section', 'chapter', 'chapter_section', 'verse'] as const).map(
            (entityType) =>
                ({
                    key: `${entityType}.delete`,
                    schemaFamily: 'scripture',
                    entityType,
                    family: 'delete',
                    label: 'Delete',
                    menuGroup: 'danger',
                    controlLevel: 'entity',
                    uiMode: 'confirmation',
                    backendStatus: 'needs_conscious_backend',
                    risk: 'dangerous',
                    requiredCapability: 'delete',
                    backendAction: {
                        type: 'schema_action',
                        actionKey: 'delete',
                    },
                    fullEditCategory: 'Advanced / Technical',
                    ...unavailable(NEEDS_BACKEND),
                }) satisfies ConsciousAdminActionDefinition,
        ),
        {
            key: 'content_block.duplicate',
            schemaFamily: 'scripture',
            entityType: 'content_block',
            family: 'duplicate',
            label: 'Duplicate block',
            menuGroup: 'structure',
            controlLevel: 'card',
            uiMode: 'confirmation',
            backendStatus: 'old_endpoint_only',
            risk: 'protected',
            requiredCapability: 'duplicate',
            backendAction: {
                type: 'old_endpoint_fallback',
                routeName: 'content_block.duplicate',
            },
            fullEditCategory: 'Advanced / Technical',
            ...unavailable(OLD_ENDPOINT_ONLY),
        },
        {
            key: 'content_block.manage',
            schemaFamily: 'scripture',
            entityType: 'content_block',
            family: 'manage',
            label: 'Edit block type/config/status',
            menuGroup: 'structure',
            controlLevel: 'card',
            uiMode: 'full_edit',
            backendStatus: 'old_endpoint_only',
            risk: 'protected',
            requiredCapability: 'manage',
            backendAction: {
                type: 'old_endpoint_fallback',
                routeName: 'content_block.update',
            },
            fullEditCategory: 'Advanced / Technical',
            ...unavailable(OLD_ENDPOINT_ONLY),
        },
        {
            key: 'media_assignment.manage',
            schemaFamily: 'scripture',
            entityType: 'media_assignment',
            family: 'manage',
            label: 'Manage media assignment',
            menuGroup: 'media',
            controlLevel: 'card',
            uiMode: 'drawer',
            backendStatus: 'old_endpoint_only',
            risk: 'protected',
            requiredCapability: 'manage',
            backendAction: {
                type: 'old_endpoint_fallback',
                routeName: 'media_assignment.update',
            },
            fullEditCategory: 'Media',
            ...unavailable(OLD_ENDPOINT_ONLY),
        },
        {
            key: 'verse_meta.manage',
            schemaFamily: 'scripture',
            entityType: 'verse',
            family: 'manage',
            label: 'Manage verse meta',
            menuGroup: 'support',
            controlLevel: 'entity',
            uiMode: 'drawer',
            backendStatus: 'old_endpoint_only',
            risk: 'protected',
            requiredCapability: 'manage',
            backendAction: {
                type: 'old_endpoint_fallback',
                routeName: 'verse_meta.update',
            },
            fullEditCategory: 'Support Data',
            ...unavailable(OLD_ENDPOINT_ONLY),
        },
        ...(['verse_translation', 'verse_commentary'] as const).flatMap(
            (entityType) =>
                [
                    {
                        key: `${entityType}.create`,
                        schemaFamily: 'scripture',
                        entityType,
                        family: 'create',
                        label:
                            entityType === 'verse_translation'
                                ? 'Add translation'
                                : 'Add commentary',
                        menuGroup: 'relations',
                        controlLevel: 'section',
                        uiMode: 'modal',
                        backendStatus: 'old_endpoint_only',
                        risk: 'protected',
                        requiredCapability: 'create',
                        backendAction: {
                            type: 'old_endpoint_fallback',
                            routeName: `${entityType}.store`,
                        },
                        fullEditCategory: 'Relations',
                        ...unavailable(OLD_ENDPOINT_ONLY),
                    },
                    {
                        key: `${entityType}.manage`,
                        schemaFamily: 'scripture',
                        entityType,
                        family: 'manage',
                        label:
                            entityType === 'verse_translation'
                                ? 'Manage translations'
                                : 'Manage commentaries',
                        menuGroup: 'relations',
                        controlLevel: 'section',
                        uiMode: 'drawer',
                        backendStatus: 'old_endpoint_only',
                        risk: 'protected',
                        requiredCapability: 'manage',
                        backendAction: {
                            type: 'old_endpoint_fallback',
                            routeName: `${entityType}.update`,
                        },
                        fullEditCategory: 'Relations',
                        ...unavailable(OLD_ENDPOINT_ONLY),
                    },
                ] satisfies ConsciousAdminActionDefinition[],
        ),
        {
            key: 'content_block.move_region',
            schemaFamily: 'scripture',
            entityType: 'content_block',
            family: 'move',
            label: 'Move block to region',
            menuGroup: 'structure',
            controlLevel: 'card',
            uiMode: 'drawer',
            backendStatus: 'future',
            risk: 'protected',
            requiredCapability: 'move',
            backendAction: { type: 'none' },
            fullEditCategory: 'Structure & Parentage',
            ...unavailable(FUTURE),
        },
    ];
