import { CONTENT_FIELD_CONFIGS as BOOK_CONTENT_FIELD_CONFIGS, CONTENT_TABLE_SCHEMAS } from "../books/schema.js";
import { EXPLANATION_FIELD_CONFIGS, EXPLANATION_TABLE_SCHEMAS } from "../explanations/schema.js";
import { CHARACTER_FIELD_CONFIGS, CHARACTER_TABLE_SCHEMAS } from "./characters-schema.js";
import { CMS_FIELD_CONFIGS, CMS_TABLE_SCHEMAS } from "./cms-schema.js";
import { PERMISSIONS_CONTENT_FIELD_CONFIGS, PERMISSIONS_CONTENT_TABLE_SCHEMAS } from "./permissions-schema.js";

export const ALL_CONTENT_FIELD_CONFIGS = Object.freeze({
    ...BOOK_CONTENT_FIELD_CONFIGS,
    ...EXPLANATION_FIELD_CONFIGS,
    ...CHARACTER_FIELD_CONFIGS,
    ...CMS_FIELD_CONFIGS,
    ...PERMISSIONS_CONTENT_FIELD_CONFIGS,
});

export const ALL_CONTENT_TABLE_SCHEMAS = Object.freeze({
    ...CONTENT_TABLE_SCHEMAS,
    ...EXPLANATION_TABLE_SCHEMAS,
    ...CHARACTER_TABLE_SCHEMAS,
    ...CMS_TABLE_SCHEMAS,
    ...PERMISSIONS_CONTENT_TABLE_SCHEMAS,
});
